name: Deploy to Render

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      run: docker build -t n8n-workflow .
      
    - name: Test Docker image
      run: |
        docker run --rm -d --name test-n8n -p 5678:5678 n8n-workflow
        sleep 10
        curl -f http://localhost:5678/healthz || exit 1
        docker stop test-n8n
